### ISSUE TITLE
Weird behavior on uploading image bigger then original canvas

### ISSUE THREAD

**Issue by CristiHuma96** [alin-corodescu/CLIW-APIx#3] opened 2018-01-10 11:05 UTC
When uploading a smaller image than the original size of the canvas, everything works as expected

When uploading a LARGER image than the original size, the difference between the original size and the size of the image is being cut off and it looks like the image is zoomed in, even though drawing on the image works normally
![capture](https://user-images.githubusercontent.com/24826863/34769591-ea138f8c-f606-11e7-8859-1d717b0250f5.PNG)

**Comment by CristiHuma96** [comment] 2018-01-10 14:37
The problem is the same even we try to ZOOM out -- it looks like we do not update the canvas properly, to resize the image, and we're stuck to the original size of the canvas

**Comment by alin-corodescu** [comment] 2018-01-11 18:03
caused by setting wrong transfer canvas dimensions, fixed now

**Closed as completed** 2018-01-11 18:03 UTC
